apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
type: Opaque
data:
  alertmanager.yaml: Z2xvYmFsOg0KICByZXNvbHZlX3RpbWVvdXQ6IDVtDQoNCnJvdXRlOg0KICBncm91cF9ieTogWydhbGVydG5hbWUnXQ0KICByZWNlaXZlcjogJ3NsYWNrLW5vdGlmaWVyJw0KICBncm91cF93YWl0OiAxMHMNCiAgZ3JvdXBfaW50ZXJ2YWw6IDFtDQogIHJlcGVhdF9pbnRlcnZhbDogM2gNCg0KcmVjZWl2ZXJzOg0KICAtIG5hbWU6ICdzbGFjay1ub3RpZmllcicNCiAgICBzbGFja19jb25maWdzOg0KICAgICAgLSBzZW5kX3Jlc29sdmVkOiB0cnVlDQogICAgICAgIGFwaV91cmw6ICdodHRwczovL2hvb2tzLnNsYWNrLmNvbS9zZXJ2aWNlcy9UMDhHRkRTTFdCMS9CMDkySlQ5NUJIUy9Vc0UzU0xMdWRPbHVGckJERElYNGtnR1cnDQogICAgICAgIHVzZXJuYW1lOiAnU2VjdXJlQmFuayBBbGVydHMnDQogICAgICAgIHRpdGxlOiAne3sgLkNvbW1vbkFubm90YXRpb25zLnN1bW1hcnkgfX0nDQogICAgICAgIHRleHQ6IHwtDQogICAgICAgICAgKvCfmqggQWxlcnQ6KiB7eyAuQ29tbW9uQW5ub3RhdGlvbnMuZGVzY3JpcHRpb24gfX0NCiAgICAgICAgICAq8J+UpyBTdGF0dXM6KiB7eyAuU3RhdHVzIH19DQogICAgICAgICAgKvCfk40gSW5zdGFuY2U6KiB7eyAuQ29tbW9uTGFiZWxzLmluc3RhbmNlIH19DQogICAgICAgICAgKvCflKUgU2V2ZXJpdHk6KiB7eyAuQ29tbW9uTGFiZWxzLnNldmVyaXR5IH19DQogICAgICAgICAge3sgd2l0aCAoaW5kZXggLkFsZXJ0cyAwKSB9fQ0KICAgICAgICAgICrij7AgVGltZToqIHt7IC5TdGFydHNBdCB9fQ0KICAgICAgICAgIHt7IGVuZCB9fQ0K
