global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3h
  receiver: discord-webhook

receivers:
  - name: discord-webhook
    webhook_configs:
      - url: 
        send_resolved: true
