apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: securebankdevacr.azurecr.io/webhook-server:v2
          ports:
            - containerPort: 9001
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /alert
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /alert
              port: 9001
            initialDelaySeconds: 2
            periodSeconds: 5
