apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: securebank
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: securebankdevacr.azurecr.io/securebank-frontend:latest
        ports:
        - containerPort: 80