apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eazy-sys/securebank
    targetRevision: main
    path: argocd/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: securebank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

