name: Build and Push Backend

on:
  push:
    branches:
      - main
    paths:
      - App/backend/**
      - .github/workflows/backend.deployment.yaml

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Log in to Azure Container Registry
        run: az acr login --name securebankdevacr

      - name: Build and push Docker image
        working-directory: ./App/backend
        run: |
          docker build -f Dockerfile -t securebankdevacr.azurecr.io/securebank-backend:${{ github.sha }} .
          docker push securebankdevacr.azurecr.io/securebank-backend:${{ github.sha }}

      - name: Update backend deployment image
        run: |
          sed -i "s|image: securebankdevacr.azurecr.io/securebank-backend:.*|image: securebankdevacr.azurecr.io/securebank-backend:${{ github.sha }}|" argocd/backend/deployment.yaml

      - name: Commit updated deployment
        run: |
          git config --global user.name 'CI Bot'
          git config --global user.email 'ci@example.com'
          git add argocd/backend/deployment.yaml
          git commit -m "CD: update backend image to ${{ github.sha }}" || echo "No changes"

      - name: Push changes to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
