name: Build backend code and Push to ACR

on:
  push:
    branches:
      - main
    paths:
      - 'App/backend/**'
      - '.github/workflows/build.backend.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-        

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false
          auth-type: ID_TOKEN
          
      - name: Log in to Azure Container Registry
        run: az acr login --name securebankdevacr

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t securebankdevacr.azurecr.io/securebank-backend:latest .
          docker push securebankdevacr.azurecr.io/securebank-backend:latest