name: Build backend and Push to ACR

on:
  push:
    branches:
      - main
    paths:
      - 'App/backend/**'
      - '.github/workflows/build.backend.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-        

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name securebankdevacr

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t securebankdevacr.azurecr.io/securebank-backend:latest .
          docker push securebankdevacr.azurecr.io/securebank-backend:latest