name: Build and Push Frontend

on:
  push:
    branches:
      - main
    paths:
      - App/backend/**
      - .github/workflows/frontend.deployment.yaml

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Log in to Azure Container Registry
        run: az acr login --name securebankdevacr

      - name: Build and push Docker image
        working-directory: ./App/frontend
        run: |
          docker build -f Dockerfile -t securebankdevacr.azurecr.io/securebank-frontend:latest .
          docker push securebankdevacr.azurecr.io/securebank-frontend:latest
